# Generated by Django 6.0.5 on 2026-05-14 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('ciment', 'Ciment'), ('fer', 'Fer à béton'), ('brique', 'Briques'), ('tole', 'Tôles'), ('sable', 'Sable'), ('gravier', 'Gravier'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('prix', models.FloatField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=255)),
                ('quantite', models.IntegerField(default=1)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('validee', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.produit')),
            ],
        ),
    ]
