# Generated by Django 6.0.5 on 2026-05-15 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='validee',
        ),
        migrations.AddField(
            model_name='commande',
            name='cree_par_employe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='prix_unitaire',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('validee', 'Validée'), ('annulee', 'Annulée')], default='validee', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='total_commande',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
